[project]
tool = "create"
project = "bashlib-create"
version = "0.1.0"
author = "Jachin Minyard"
repo="https://github.com/JMinyard1335/bashlib-create"
description = "A bashlib tool that creates template (files, scritps, projects)."

[directories]
lib = "lib"
libexec = "libexec"
man = "man"

[dependencies]
style="https://github.com/JMinyard1335/bashlib-style"
