#!/usr/bin/env bash
# Used to create full bash projects.
#
# When creating via CLI flags the name and tool flags are required


create_project_tool_name="create"
create_project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
create_project_lib_dir=""

if [[ "$create_project_dir" == "${HOME}/.local/libexec/${create_project_tool_name}" ]]; then
    create_project_lib_dir="${HOME}/.local/lib/${create_project_tool_name}"
elif [[ "$create_project_dir" == "/usr/local/libexec/${create_project_tool_name}" ]]; then
    create_project_lib_dir="/usr/local/lib/${create_project_tool_name}"
elif [[ -d "${create_project_dir}/../lib" ]]; then
    create_project_lib_dir="${create_project_dir}/../lib"
else
    printf '\e[1;31m[Error]\e[0m: Unable to locate the %s library files.\n' \
           "${create_project_tool_name}" >&2
    exit 1
fi

source "${create_project_lib_dir}"/internal/bashlib_create.bash
source "$HOME"/.local/lib/style/bashlib_style.bash

create_project_version="0.1.0"

create_project_usage() {
    helpmenu_print_title "Bashlib Create Project"
    helpmenu_print_subtitle "Used to generate a new baps project."
    echo
    helpmenu_print_header "Description"
    echo -e "\t Generates all the needed files for a basic bash package."
    echo "Running without options will prompt the user, or the info can be passed"
    echo "via cmd line flags."
    echo
    echo "If using the flags the minimum of --name & --tool are required."
    echo 
    helpmenu_print_header "Usage"
    echo "Usage: create [options]"
    echo
    helpmenu_print_header "Options"
    helpmenu_print_option "-h | --help" "Show this help message and exit."
    helpmenu_print_option "-v | --version" "Show the version number and exit."
    helpmenu_print_option "-c | --create" "Creates a new project (interactive)"
    helpmenu_print_option "-n | --name" "Name of the project."
    helpmenu_print_option "-t | --tool" "Name of the main tool entry point."
    helpmenu_print_option "-a | --author" "Name of the author. (optional)"
    helpmenu_print_option "-r | --repo" "Name of the git repo. (optional)"
    helpmenu_print_option "-d | --desc" "short description of the project (optional)"
    echo
    helpmenu_print_header "Examples"
    helpmenu_print_example "create project"
    helpmenu_print_example "create project" "  --name 'my-project' --tool 'tool'"
    helpmenu_print_example "create project" "  -n 'my-project' -t 'tool' -r 'https://link-to-repo'"
    echo
}


create_project_parse() {
    local p_name="" t_name="" a_name="" repo="" desc="" project_dir=""
    [[ "$#" -eq 0 ]] && { print_error "must give some options"; create_project_usage ; exit 1; }
    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            -h|--help)
                create_project_usage
                exit 0
                ;;
            -v|--version)
		println_tag "$style_cyan" "Create Project Version" "$create_project_version"
                exit 0
                ;;
	    -c|--create)	# Create the project interactivly then exit.
		if create_project; then
		    exit 0
		else
		    exit 1
		fi
		;;
	    
	    -n|--name)
		[[ "$#" -lt 2 ]] && { print_error "no arg given for $1"; exit 1; }
		p_name="$2"
		shift 2
		;;
	    -t|--tool)
		[[ "$#" -lt 2 ]] && { print_error "no arg given for $1"; exit 1; }
		t_name="$2"
		shift 2
		;;
	    -a|--author)
		[[ "$#" -lt 2 ]] && { print_error "no arg given for $1"; exit 1; }
		a_name="$2"
		shift 2
		;;
	    -r|--repo)
		[[ "$#" -lt 2 ]] && { print_error "no arg given for $1"; exit 1; }
		repo="$2"
		shift 2
		;;
	    -d|-desc)
		[[ "$#" -lt 2 ]] && { print_error "no arg given for $1"; exit 1; }
		desc="$2"
		shift 2
		;;
            *)
                echo "Unknown option: $1" >&2
                create_project_usage
                exit 1
                ;;
        esac
    done

	[[ -z "$t_name" ]] && { print_error "--tool must be given if making a project with flags." ; exit 1; }
	[[ -z "$p_name" ]] && { print_error "--name must be given if making a project with flags." ; exit 1; }
	project_dir="$(pwd)/$p_name"
	echo -e "Creating project in \e[36m$project_dir\e[0m..."
	
	create_mkdirs "$project_dir" || return 1
	create_touch_files "$project_dir" "$t_name" "$a_name" "$repo" "$desc" || return 1
}


# Put any tool specific setup code here
create_project_main() {
    create_project_parse "$@"
}


# Main is only called if this script is run directly, if it is sourced then main is not called.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    create_project_main "$@"
fi

